#!/usr/bin/env bash

set -eu

function cmdcheck() { type >/dev/null 2>&1 "$@"; }
! cmdcheck git && echo 1>&2 'Not found git command' && return 1

function abspath() {
  [[ $1 =~ ^/.* ]] && printf '%s' "$1" || printf '%s' "$PWD/${1#./}"
}

function help() {
  echo "$(basename "$0") [git url] (-O output_path)" 1>&2
  exit 1
}
function git_wget_main() {
  local dst_path="$PWD"
  [[ $# -lt 1 ]] && help
  [[ $1 =~ ^(-h|-{1,2}help)$ ]] && help && exit 1
  local url="$1"
  if [[ $# -ge 2 ]]; then
    if [[ $2 == '-O' ]] && [[ -n $3 ]]; then
      dst_path=$(abspath "$3")
    else
      help
    fi
  fi

  GIT_WGET_TMP_DIR=${GIT_WGET_TMP_DIR:-}
  GIT_WGET_DEBUG=${GIT_WGET_DEBUG:-}
  GIT_SPARSE_CHECKOUT_ENABLE=${GIT_SPARSE_CHECKOUT_ENABLE:-1}
  GITHUB_RAW_FILE_ACCESS_FLAG=${GITHUB_RAW_FILE_ACCESS_FLAG:-0}

  if [[ $GITHUB_RAW_FILE_ACCESS_FLAG != 0 ]]; then
    local filename
    filename="$(basename "$url")"
    # NOTE: maybe file url shortcut command
    if [[ $filename =~ \. ]]; then
      if [[ -d $dst_path ]]; then
        dst_path="${dst_path}/${filename}"
      fi
      # NOTE: this can be return dir html
      # wget "${url}?raw=true" -O "$dst_path"
      local raw_file_url
      raw_file_url="${url//github.com/raw.githubusercontent.com}"
      raw_file_url="${raw_file_url//blob\//}"
      if wget "$raw_file_url" -O "$dst_path"; then
        return
      else
        printf '%s' "[log] maybe this url refer dir (not file)"
      fi
    fi
  fi

  # NOTE: setup git clone tmp dir
  if [[ -z $GIT_WGET_TMP_DIR ]]; then
    GIT_WGET_TMP_DIR=$(mktemp -d "/tmp/$(basename "$0").$$.tmp.XXXXXX")
    local trap_cmd="[[ -d $GIT_WGET_TMP_DIR ]] && rm -rf $GIT_WGET_TMP_DIR"
    # shellcheck disable=SC2064
    [[ -z $GIT_WGET_DEBUG ]] && trap "$trap_cmd" 0 1 2 3 15
  else
    mkdir -p "$GIT_WGET_TMP_DIR" || exit $?
  fi
  pushd "$GIT_WGET_TMP_DIR" >/dev/null 2>&1 || return 1
  [[ -n $GIT_WGET_DEBUG ]] && echo 1>&2 "[DEBUG][tmp dir]: $GIT_WGET_TMP_DIR"

  local branch
  local clone_url
  local target_path
  branch=$(printf '%s' "$url" | sed -E 's:^.*/(tree|blob)/([^/]*)/.*$:\2:g')
  clone_url=$(printf '%s' "$url" | sed -E 's:^(.*)/(tree|blob)/[^/]*/.*$:\1:g')
  target_path=$(printf '%s' "$url" | sed -E 's:^.*/(tree|blob)/[^/]*/(.*)$:\2:g')
  [[ -z $branch ]] && echo "Cannot get branch name from '$url'" && return 1
  [[ -z $clone_url ]] && echo "Cannot get clone url from '$url'" && return 1
  [[ -z $target_path ]] && echo "Cannot get target path from '$url'" && return 1
  local repo_name
  repo_name=$(printf '%s' "$url" | sed -E 's:^.*/github.com/[^/]*/([^/]*)/(.*)$:\1:g')
  [[ -z $repo_name ]] && echo "Cannot get repo name from '$url'" && return 1
  if [[ ! -e $repo_name ]]; then
    # NOTE: v1.7.0~?
    # FYI: [version control \- Sparse checkout in Git 1\.7\.0? \- Stack Overflow]( https://stackoverflow.com/questions/2336580/sparse-checkout-in-git-1-7-0 )
    if [[ $GIT_SPARSE_CHECKOUT_ENABLE == 0 ]]; then
      git clone -b "$branch" --depth 1 "$clone_url" || return 1
    else
      # NOTE: sparse checkout version
      mkdir -p "$repo_name"
      pushd "$repo_name"
      git init
      git config core.sparsecheckout true
      git remote add origin "$clone_url"
      mkdir -p .git/info
      echo "$target_path" >.git/info/sparse-checkout
      if cmdcheck nkf; then
        nkf -w --in-place .git/info/sparse-checkout
      fi
      git pull --depth=1 origin "$branch"
      popd
    fi
  else
    pushd "$repo_name" >/dev/null 2>&1 || return 1
    # NOTE: if there is a lot of diff, use upper git clone code
    git pull || return 1
    popd >/dev/null 2>&1 || return 1
  fi
  [[ -n $GIT_WGET_DEBUG ]] && echo 1>&2 '[DEBUG][command]' cp -R "$repo_name/$target_path" "$dst_path"
  cp -R "$repo_name/$target_path" "$dst_path" || return 1
  popd >/dev/null 2>&1 || return 1
}

git_wget_main "$@"
